#!/bin/bash

function untilsuccessful() {
        "$@"
        while [ $? -ne 0 ]; do
                echo Retrying...
                sleep 1
                "$@"
        done
}

LOCAL_IP=`hostname --ip-address`
IP=${IP:-$LOCAL_IP}
SEED=$1
CB_USERNAME=${CB_USERNAME:-Administrator}
CB_PASSWORD=${CB_PASSWORD:-Password}
CB_RAMSIZE=${CB_RAMSIZE:-4096}
CB_DEFAULT_BUCKET_NAME=${CB_DEFAULT_BUCKET_NAME:-default}
CB_DEFAULT_BUCKET_RAMSIZE=${CB_DEFAULT_BUCKET_RAMSIZE:-128}

# Start Couchbase in background
su - couchbase -c "/opt/couchbase/bin/couchbase-server -- -noinput" &
PID=$!

# Init Couchbase
untilsuccessful couchbase-cli node-init -c $IP \
        --node-init-data-path=/data \
        --node-init-index-path=/index

if [ "$IP" = "$LOCAL_IP" ]; then
        untilsuccessful curl -v -X POST -u $CB_USERNAME:$CB_PASSWORD \
                http://127.0.0.1:8091/node/controller/rename -d hostname=${HOSTNAME:$IP}
fi


if [ -n "$SEED" ]; then
        echo "Make Couchbase ($IP) join the cluster via $SEED"
        untilsuccessful couchbase-cli server-add -c $SEED \
                --user=$CB_USERNAME --password=$CB_PASSWORD \
                --server-add=$IP
        untilsuccessful couchbase-cli rebalance -c $SEED \
                --user=$CB_USERNAME --password=$CB_PASSWORD
else
        echo "Make Couchbase ($IP) the first cluster node"
        untilsuccessful couchbase-cli cluster-init -c $IP \
                --cluster-init-username=$CB_USERNAME \
                --cluster-init-password=$CB_PASSWORD \
                --cluster-init-ramsize=$CB_RAMSIZE
        untilsuccessful couchbase-cli bucket-create -c $IP \
                -u $CB_USERNAME -p $CB_PASSWORD \
                --bucket=$CB_DEFAULT_BUCKET_NAME --bucket-ramsize=$CB_DEFAULT_BUCKET_RAMSIZE
fi

# Wait indefinitely on Couchbase process
wait $PID
